site_name: Lazuli Devkit
plugins:
  - search
nav:
  - ä¸»é¡µ: index.md
  - é—®é¢˜: issues.md
  - æŒ‡å—:
    - å¿«é€Ÿå¼€å§‹: guide/start.md
    - è¯­è¨€æ–‡ä»¶: guide/lang.md
    - Lazuli Core:
      - ç®€è¿°: guide/core/interview.md  
      - åˆå§‹åŒ–æ¨¡ç»„: guide/core/init.md
      - è·å–æ¨¡ç»„ä¿¡æ¯: guide/core/get-metadata.md
    - Lazuli API:
      - Â®ï¸æ³¨å†Œ: guide/api/register.md
      - ğŸ“ƒæ–‡ç« : guide/api/article.md
      - ğŸ“•ä»»åŠ¡: guide/api/quest.md
      - ğŸ‘£ç»„ä»¶: guide/api/component.md
  - æ–‡æ¡£:
      - Lazuli Core: reference/core/globals.md
      - Lazuli Api: reference/api/globals.md
      - Lazuli Utils: reference/utils/globals.md
      - Lazuli Logger: reference/logger/globals.md
      - Lazuli GameData: reference/game-data/globals.md
markdown_extensions:
  - attr_list
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - footnotes
  - pymdownx.tabbed:
      alternate_style: true
theme:
  name: material
  logo: assets/bedrock.png
  favicon: assets/bedrock.png
  features:
    - navigation.footer
    - header.autohide
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate
    - navigation.expand
    - navigation.sections
    - content.code.copy
  icon:
    repo: fontawesome/brands/git-alt
    edit: material/pencil
    view: material/eye
  palette:
    primary: white
